### PR TITLE
Landing page ui done

### PR DESCRIPTION
**Pull request by Sorphy**
Screenshot 2024-01-20 at 12 09 16

### CODE REVIEW

**Review by Don-christo — APPROVED** [review]
Great work. LGTM!

**Review by Afinjuomo — CHANGES_REQUESTED** [review]
I thought we were to use tailwind css

**Comment by Don-christo** [comment]
> I thought we were to use tailwind css

She used tailwindCSS, or where exactly are you talking about?

**Comment by Afinjuomo** [comment]
> > I thought we were to use tailwind css
> 
> She used tailwindCSS, or where exactly are you talking about?

I just saw that now, I omitted that

**Comment by Sorphy** [comment]
What's delaying the merge, please

**Review by Afinjuomo — APPROVED** [review]

**Pull request merged**
